const { CHECKOUT_API_KEY, MERCHANT_ACCOUNT, API_VERSION = 'v1', TESTING_ENVIRONMENT = 'test', TEST_SERVICE_URL } = process.env;

const serviceUrls = {
    test: `${TEST_SERVICE_URL}/${API_VERSION}`
};

const CHECKOUT_SERVICE_URL = serviceUrls[TESTING_ENVIRONMENT] || TESTING_ENVIRONMENT;

module.exports = {
    CHECKOUT_API_KEY,
    CHECKOUT_URL: CHECKOUT_SERVICE_URL,
    MERCHANT_ACCOUNT
};
